<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDrZLiP7\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDrZLiP7/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDrZLiP7.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDrZLiP7\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerDrZLiP7\App_KernelDevDebugContainer([
    'container.build_hash' => 'DrZLiP7',
    'container.build_id' => 'ba17bbc2',
    'container.build_time' => 1679755961,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDrZLiP7');
